gp:
  generations: 10
  populationSize: 100
  mutationRate: 1
  mutationOperators:
    - GNR
  iterationsPerBug: 2
  numberOfThreads: 1

defects4j:
  testCaseSelection:
    method: identifier
    selection:
      #PASS LRRemoval Compress: [31]
      #PASS LRRelocation Closure: [13]
      #PASS BEM (may be overfit) BEM Closure: [62]
      #PASS BERReduction Closure 18
      #TRYING BERExpansion Closure 113
      #TRYING GNR Lang 26

      Lang: [26]


output:
  csv: summary
  javadoc: false
  uploadToPatchViewer: false
  uploadToGeneratePatches: false
  gp: true