gp:
  generations: 10
  populationSize: 1_000
  crossoverRate: 0.75
  mutationRate: 0.05
  mutationOperators: all

defects4J:
  testCaseSelection:
    method: identifier
    selection:
      Chart: all
      Closure: [1-4, 6, 8-12] # 1,2,3,4,6,8,9,10,11,12

output:
  summary:
    csv: summary

  full:
    jar: complete