gp:
  generations: 5
  populationSize: 10
  mutationRate: 1
  mutationOperators:
    - BERExpansion
  iterationsPerBug: 1
  numberOfThreads: 2 # (2 works best for this laptop)

defects4j:
  testCaseSelection:
    method: identifier
    selection:
      #PASS LRRemoval Compress: [31]
      #PASS LRRelocation Closure: [13]
      #PASS BEM (may be overfit) BEM Closure: [62]
      #PASS BERReduction Closure 18
      #TRYING BERExpansion Closure 113

      Closure: [113]

      #Lang: [9]
      #Time: [4]
      #Closure: all
      #Lang: [1]
      #Lang: [1]
      #Lang: [1,3-10]
      #Chart: all
      #Closure: [1-4, 6, 8-12] # 1,2,3,4,6,8,9,10,11,12

output:
  csv: summary
  javadoc: false
  uploadToPatchViewer: false
  uploadToGeneratePatches: false
  gp: false