gp:
  generations: 10
  populationSize: 50
  mutationRate: 1
  mutationOperators:
    - LRR
  iterationsPerBug: 10
  numberOfThreads: 1

defects4j:
  testCaseSelection:
    method: identifier
    selection:
      Compress: [27, 31]
      Cli: [19, 32]
      Closure: [6, 11, 13, 46, 78, 102, 115, 117, 126]
      Jsoup: [24, 40, 49, 64]
      Lang: [10, 53]
      Math: [50]
      JacksonDatabind: [83, 102]

output:
  csv: summary
  javadoc: false
  uploadToPatchViewer: false
  uploadToGeneratePatches: true
  gp: true