gp:
  generations: 1
  populationSize: 1
  mutationRate: 1
  mutationOperators:
    - MutationOperator1
  iterationsPerBug: 1
  numberOfThreads: 1 # (2 works best for this laptop)

defects4j:
  testCaseSelection:
    method: identifier
    selection:
      Lang: [1]
      #Lang: [1]
      #Lang: [1,3-10]
      #Chart: all
      #Closure: [1-4, 6, 8-12] # 1,2,3,4,6,8,9,10,11,12

output:
  csv: summary
  javadoc: false
  patches: false
  gp: true