gp:
  generations: 10
  populationSize: 50
  mutationRate: 1
  mutationOperators:
    - LRR
  iterationsPerBug: 10
  numberOfThreads: 2

defects4j:
  testCaseSelection:
    method: identifier
    selection:
      Compress: [27, 31]
      Cli: [19, 32]
      Closure: [6, 11, 13, 46, 78, 102, 115, 117, 126]
      Jsoup: [24, 40, 49, 64]
      Lang: [10, 53]
      Math: [50]
      JacksonDatabind: [83, 102]

output:
  csv: summary
  javadoc: false
  uploadToPatchViewer: false
  uploadToGeneratePatches: false
  gp: true


# Docker run command to copy over the users config.yml if present and map output and javadoc directories
# docker run -v ${pwd}/config.yml:/APRFramework/config.yml -v ${pwd}/output/:/output/ -v ${pwd}/javadoc/:/javadoc/ dev  -> command to users
# docker run -v ${pwd}/:/APRFramework dev          -> debugging

# docker run -v %cd%/config.yml:/APRFramework/config.yml -v %cd%/output/:/output/ -v %cd%/javadoc/:/javadoc/ dev