name: Docker CI for APRFramework and Defects4j

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Dockerfile -> Development workflow
        run: docker build -t fentonreid/aprframework:$(git rev-parse --short "$GITHUB_SHA") .

      - name: Running tests for APRFramework
        run: | 
            docker run fentonreid/aprframework:$(git rev-parse --short "$GITHUB_SHA") mvn test
            
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push to Dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/aprframework:$(git rev-parse --short "$GITHUB_SHA")
